nodes:
  - address: <public ip address>
    internal_address: <private ip address>
    user: ubuntu
    role: [controlplane, worker, etcd]
    ssh_key_path: <path your private key default ~/.ssh/id_rsa>
  - address: <public ip address>
    internal_address: <private ip address>
    user: ubuntu
    role: [controlplane, worker, etcd]
    ssh_key_path: <path your private key default ~/.ssh/id_rsa>
  - address: <public ip address>
    internal_address: <private ip address>
    user: ubuntu
    role: [controlplane, worker, etcd]
    ssh_key_path: <path your private key default ~/.ssh/id_rsa>

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h


ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"

kubernetes_version: <latest version>
